version: "3.7"

services:
  node:
    build:
      context: .
    container_name: "ngcash_app"
    ports:
      - "3333:3333"
    volumes: 
      - ./src:/app  
    depends_on:
      - db

  db:
    image: postgres
    container_name: database_ngcash
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local